package dev.cyclone.cloak

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Parity vectors generated by forge/cloak_forge with seed "ab" * 32 and name
 * "Vault 01". If this test breaks, the on-device forge and the desktop forge
 * have drifted apart, and one of them must be corrected, never both silently.
 */
class CloakForgeTest {
    private val seed = "ab".repeat(32)

    @Test
    fun identifiersMatchThePythonForge() {
        val ids = CloakForge.deriveIdentifierBundle(seed)
        assertEquals("3a4cf3a7fcd4e8cb", ids["android_id"])
        assertEquals("d3500169-d39a-40b1-bcfa-f9d9d1739be7", ids["advertising_id"])
        assertEquals("3d2eb31f-1124-489c-bcd6-61b985491917", ids["app_set_id"])
        assertEquals("1A:35:32:1E:77:25", ids["mac"])
        assertEquals("3A:B4:66:9A:D8:54", ids["bt_mac"])
        assertEquals("472186978248637", ids["imei_primary"])
        assertEquals("710989943352422", ids["imei_secondary"])
        assertEquals("2622829857001513606", ids["sim_serial"])
        assertEquals("f043b6a655d7a57a", ids["gsf_id"])
        assertEquals(
            "f2b9c7904bec4ec0755b7aec3eca856e1deb43ab9cbd564f038af27837d568d3",
            ids["widevine_id"],
        )
        assertEquals("U6UV1SJBJET5", ids["serial"])
    }

    @Test
    fun profileIdMatchesThePythonForge() {
        val profile = CloakForge.forgeProfile("Vault 01", seed, "pixel_7")
        assertEquals("a15ece73-55a2-5b1d-9b66-c695a95776b7", profile.getString("id"))
    }

    @Test
    fun userAgentMatchesThePythonForge() {
        val profile = CloakForge.forgeProfile("Vault 01", seed, "pixel_7")
        assertEquals(
            "Mozilla/5.0 (Linux; Android 13; Pixel 7) " +
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.5640.47 Safari/537.36",
            profile.getJSONObject("ua").getString("value"),
        )
    }

    @Test
    fun forgedProfilePassesStoreValidation() {
        for (template in CloakForge.templateNames()) {
            val profile = CloakForge.forgeProfile("Vault 01", seed, template)
            assertNull(CloakStore.validate(profile))
        }
    }

    @Test
    fun forgingIsDeterministic() {
        val first = CloakForge.forgeProfile("Vault 01", seed, "pixel_7").toString()
        val again = CloakForge.forgeProfile("Vault 01", seed, "pixel_7").toString()
        assertEquals(first, again)
    }

    @Test
    fun pixel4TemplateForgesAValidProfile() {
        val profile = CloakForge.forgeProfile("Vault 01", seed, "pixel_4")

        assertNull(CloakStore.validate(profile))
        assertEquals("Pixel 4", profile.getJSONObject("device").getString("model"))
        assertEquals("flame", profile.getJSONObject("device").getString("device"))
    }

    @Test
    fun newDeviceProfilesGetIndependentIdentifiers() {
        val first = CloakForge.forgeNewProfile("My device", "pixel_7")
        val second = CloakForge.forgeNewProfile("My device", "pixel_7")

        assertNull(CloakStore.validate(first))
        assertNull(CloakStore.validate(second))
        assertNotEquals(first.getString("seed"), second.getString("seed"))
        assertNotEquals(
            first.getJSONObject("identifiers").getString("android_id"),
            second.getJSONObject("identifiers").getString("android_id"),
        )
    }
}
